const FETCH_TEAMS_START = 'FETCH_TEAMS_START';
const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
const FETCH_TEAMS_FAIL = 'FETCH_TEAMS_FAIL';

export {FETCH_TEAMS_START,FETCH_TEAMS_SUCCESS,FETCH_TEAMS_FAIL}