const FETCH_PLAYERS_START = 'FETCH_PLAYERS_START';
const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
const FETCH_PLAYERS_FAIL = 'FETCH_PLAYERS_FAIL';

export {FETCH_PLAYERS_START,FETCH_PLAYERS_SUCCESS,FETCH_PLAYERS_FAIL}